package org.myazure.weixin.constant;

public class APICount {

	public int ACCESS_TOKEN_COUNT = 0;
	public int CUSTOM_MENU_CREAT = 0;
	public int QUERY_CUSTOM_MENU = 0;
	public int CUSTOM_MENU_DELETE = 0;
	public int CREAT_GROUP = 0;
	public int QUERY_GROUP = 0;
	public int MODIFY_GROUP_NAME = 0;
	public int MOVE_USER_GROUP = 0;
	public int UPLOAD_MUTIMEDIA_FILES = 0;
	public int DOWNLOAD_MUTIMEDIA_FILES = 0;
	public int SEND_CUSTOMER_SERVICE_NEWS = 0;
	public int ADVANCED_MASS_INTERFACE = 0;
	public int UPLOAD_PICTURE_MESSAGE_INTERFACE = 0;
	public int DELETE_PICTURE_MESSAGE_INTERFACE = 0;
	public int GET_QRCODE_WITH_PARAMETERS = 0;
	public int GET_THE_FOLLOWERS_LIST = 0;
	public int GET_FOLLOWERS_BASIC_INFOMATION = 0;
	public int GET_WEB_AUTHORIZATION_ACCESS_TOKEN = 0;
	public int REFRESH_WEB_AUTHORIZATION_ACCESS_TOKEN = 0;
	public int WEB_ACCESS_TO_GET_USER_INFOMATION_WITHOUT_AUTHORIZATION = 0;
	public int SET_USER_NOTES = 0;

	public int ACCESS_TOKEN_COUNT_LIMIT = 2000;
	public int CUSTOM_MENU_CREAT_LIMIT = 1000;
	public int QUERY_CUSTOM_MENU_LIMIT = 10000;
	public int CUSTOM_MENU_DELETE_LIMIT = 1000;
	public int CREAT_GROUP_LIMIT = 1000;
	public int QUERY_GROUP_LIMIT = 1000;
	public int MODIFY_GROUP_NAME_LIMIT = 1000;
	public int MOVE_USER_GROUP_LIMIT = 100000;
	public int UPLOAD_MUTIMEDIA_FILES_LIMIT = 5000;
	public int DOWNLOAD_MUTIMEDIA_FILES_LIMIT = 10000;
	public int SEND_CUSTOMER_SERVICE_NEWS_LIMIT = 500000;
	public int ADVANCED_MASS_INTERFACE_LIMIT = 100;
	public int UPLOAD_PICTURE_MESSAGE_INTERFACE_LIMIT = 10;
	public int DELETE_PICTURE_MESSAGE_INTERFACE_LIMIT = 10;
	public int GET_QRCODE_WITH_PARAMETERS_LIMIT = 100000;
	public int GET_THE_FOLLOWERS_LIST_LIMIT = 500;
	public int GET_FOLLOWERS_BASIC_INFOMATION_LIMIT = 5000000;
	public int GET_WEB_AUTHORIZATION_ACCESS_TOKEN_LIMIT = -1;
	public int REFRESH_WEB_AUTHORIZATION_ACCESS_TOKEN_LIMIT = -1;
	public int WEB_ACCESS_TO_GET_USER_INFOMATION_WITHOUT_AUTHORIZATION_LIMIT = -1;
	public int SET_USER_NOTES_LIMIT = 10000;

	// public final int ACCESS_TOKEN_COUNT_DEVELOPER_LIMIT = 200;
	// public final int CUSTOM_MENU_CREAT_DEVELOPER_LIMIT = 100;
	// public final int QUERY_CUSTOM_MENU_DEVELOPER_LIMIT = 1000;
	// public final int CUSTOM_MENU_DELETE_DEVELOPER_LIMIT = 100;
	// public final int CREAT_GROUP_DEVELOPER_LIMIT = 100;
	// public final int QUERY_GROUP_DEVELOPER_LIMIT = 100;
	// public final int MODIFY_GROUP_NAME_DEVELOPER_LIMIT = 100;
	// public final int MOVE_USER_GROUP_DEVELOPER_LIMIT = 1000;
	// public final int UPLOAD_MUTIMEDIA_FILES_DEVELOPER_LIMIT = 500;
	// public final int DOWNLOAD_MUTIMEDIA_FILES_DEVELOPER_LIMIT = 1000;
	// public final int SEND_CUSTOMER_SERVICE_NEWS_DEVELOPER_LIMIT = 50000;
	// public final int ADVANCED_MASS_INTERFACE_DEVELOPER_LIMIT = 0;
	// public final int UPLOAD_PICTURE_MESSAGE_INTERFACE_DEVELOPER_LIMIT = 0;
	// public final int DELETE_PICTURE_MESSAGE_INTERFACE_DEVELOPER_LIMIT = 0;
	// public final int GET_QRCODE_WITH_PARAMETERS_DEVELOPER_LIMIT = 10000;
	// public final int GET_THE_FOLLOWERS_LIST_DEVELOPER_LIMIT = 100;
	// public final int GET_FOLLOWERS_BASIC_INFOMATION_DEVELOPER_LIMIT = 500000;
	// public final int GET_WEB_AUTHORIZATION_ACCESS_TOKEN_DEVELOPER_LIMIT = -1;
	// public final int REFRESH_WEB_AUTHORIZATION_ACCESS_TOKEN_DEVELOPER_LIMIT =
	// -1;
	// public final int
	// WEB_ACCESS_TO_GET_USER_INFOMATION_WITHOUT_AUTHORIZATION_DEVELOPER_LIMIT =
	// -1;
	// public final int SET_USER_NOTES_DEVELOPER_LIMIT = 0;
}
